"""contact unique add user

Revision ID: fee87ceece57
Revises: 3877acf4827b
Create Date: 2024-01-20 20:07:54.208719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee87ceece57'
down_revision: Union[str, None] = '3877acf4827b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('first_last_email', 'contacts', type_='unique')
    op.create_unique_constraint('first_last_email', 'contacts', ['first_name', 'last_name', 'email', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('first_last_email', 'contacts', type_='unique')
    op.create_unique_constraint('first_last_email', 'contacts', ['first_name', 'last_name', 'email'])
    # ### end Alembic commands ###
